### PR TITLE
Upgrade to Julia 0.4.7 and Jupyter 4.2.x

### PR DESCRIPTION
**Pull request by nkottary**
Change julia:v0.4.x base image to include Julia v0.4.7 and Jupyter 4.2.x

### CODE REVIEW

**Comment by tanmaykm** [comment]
:+1:

**Comment by tanmaykm** [comment]
I see this error:

```
Step 5 : RUN git clone --recursive --branch 4.2.x https://github.com/jupyter/notebook; cd notebook; python setup.py install; cd ..; rm -rf notebook
 ---> Running in d6c0a7c8ede4
Cloning into 'notebook'...
running install
running build
running build_py
running jsversion
running css
running jsdeps
npm unavailable
> bower install --allow-root --config.interactive=false
Failed to run bower: [Errno 2] No such file or directory
You can install js dependencies with `npm install`
rebuilding js and css failed. The following required files are missing: ['notebook/static/components', 'notebook/static/notebook/js/main.min.js', 'notebook/static/tree/js/main.min.js', 'notebook/static/edit/js/main.min.js', 'notebook/static/terminal/js/main.min.js', 'notebook/static/auth/js/main.min.js', 'notebook/static/style/ipython.min.css', 'notebook/static/style/style.min.css']
error: [Errno 2] No such file or directory
```

May be there are some differences in the dependencies now?

**Comment by nkottary** [comment]
Shall I also add v0.3.12 to this? it will save some time in the JuliaBox build.

**Comment by tanmaykm** [comment]
JuliaBox will also needs 0.5, and more later.
May be better to have another `latest` that has all recent versions?

**Comment by tanmaykm** [comment]
In reality we may run into problems sooner or later, because not all Julia and package versions would work with the same system/dependent library versions.

I think there will be a need for multiple JuliaBox images, based on separate base images. But we can use one consolidated `latest` image till then.

**Comment by nkottary** [comment]
Closing this as changes are covered in #14

**Pull request closed without merging**
